apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis-pvt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-redis
  template:
    metadata:
      labels:
        app: flask-redis
    spec:
      containers:
        - name: flask
          image: ghcr.io/badri/flask-redis:1.0
          imagePullPolicy: Always
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DEBUG
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name: ghcr-creds
