apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-redis-init
  template:
    metadata:
      labels:
        app: flask-redis-init
    spec:
      initContainers:
        - name: check-redis
          image: alpine
          command: ['/bin/sh', '-c', 'apk add --no-cache netcat-openbsd && /usr/local/bin/check-redis.sh']
          env:
          - name: REDIS_HOST
            value: cache.full-stack.svc.cluster.local
          volumeMounts:
          - name: redis-check-script
            mountPath: /usr/local/bin/check-redis.sh
            subPath: check-redis.sh
      containers:
        - name: flask
          image: ghcr.io/badri/flask-redis:1.0
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DEBUG
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 8080
      volumes:
      - name: redis-check-script
        configMap:
          name: redis-check
          defaultMode: 0755
