apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html  # Mount path for custom HTML
    - name: conf-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf  # Use subPath to mount the specific file
  volumes:
  - name: html-volume
    configMap:
      name: nginx-config
  - name: conf-volume
    configMap:
      name: custom-nginx-conf
