apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-redis
  template:
    metadata:
      labels:
        app: flask-redis
    spec:
      containers:
        - name: flask
          image: ghcr.io/badri/flask-redis:1.0
          env:
            - name: PORT
              value: "8080"
            - name: REDIS_HOST
              value: cache
            - name: REDIS_PASSWORD
              value: SuperS3cret
          ports:
            - containerPort: 8080
