apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: continuous-deployment
subjects:
- kind: ServiceAccount
  name: github
  namespace: default
roleRef:
  kind: ClusterRole
  name: continuous-deployment
  apiGroup: rbac.authorization.k8s.io
