apiVersion: v1
kind: Pod
metadata:
  name: simple-flask
  labels:
    app: simple-flask
spec:
  containers:
  - name: flask
    image: ghcr.io/badri/flask-app:1.0
    imagePullPolicy: Always
    env:
    - name: PORT
      value: "8080"
    ports:
    - containerPort: 8080
