apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  labels:
    purpose: demonstrate-multi-container
spec:
  containers:
  - name: nginx-container-1
    image: nginx
    ports:
    - containerPort: 80
  - name: nginx-container-2
    image: nginx
    ports:
    - containerPort: 81
